# Generated by Django 3.0.6 on 2020-09-11 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dnumber',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='donation_plasma_bank',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('blood', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('query1', models.CharField(max_length=10)),
                ('query2', models.CharField(max_length=10)),
                ('query3', models.CharField(max_length=10)),
                ('query4', models.CharField(max_length=10)),
                ('query5', models.CharField(max_length=10)),
                ('query6', models.CharField(max_length=10)),
                ('query7', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='plasmabankUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hospitalUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='hospital_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftitle', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=50)),
                ('submission_date', models.DateField()),
                ('plasma_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='donor_feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ftitle', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=50)),
                ('feedback', models.CharField(max_length=100)),
                ('submission_date', models.DateField()),
                ('plasma_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='blooddetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=10)),
                ('rhtype', models.CharField(max_length=20)),
                ('plate', models.CharField(max_length=20)),
                ('wbc', models.CharField(max_length=20)),
                ('antibody', models.CharField(max_length=20)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Donor')),
            ],
        ),
        migrations.CreateModel(
            name='available',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available', models.BooleanField()),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Donor')),
            ],
        ),
    ]
